### ISSUE TITLE
lacking all needed files

### ISSUE THREAD

**Issue by Zoroththeawesome** [Frankenmiller/scrolling-shooter#1]
I seem to be missing all the files needed to run the game. I need the other image files. not sure if it'll work but here is a pic. FileNotFoundError: No file 'images/background/pine1.png' found in working directory 'C:\Users\zorot\Documents\GitHub\scrolling-shooter'.

![image](https://user-images.githubusercontent.com/109387120/179327306-41de0d73-f6de-49e0-8c04-42e64d72c972.png)

**Comment by Zoroththeawesome** [comment]
alright I fixed this issue but that just lead to another file name/ path issue. Can you please upload everything on here so that I can download it all with the correct syntax?

**Comment by Frankenmiller** [comment]
Hold on, let me try

**Comment by Frankenmiller** [comment]
Try it now, I've included assets file, png's backgrounds, enemy sprites and .wav files

**Comment by Zoroththeawesome** [comment]
better, missing "button" still. I deleted everything off mine then redownloaded this new file. make sure button is included in this main thread

**Comment by Zoroththeawesome** [comment]
wait it is there give me a moment

**Comment by Zoroththeawesome** [comment]
this is what I am still missing apparently. looking for it now. maybe it just needs me to show it the path
FileNotFoundError: No file 'img/start_btn.png' found in working directory 'C:\Users\zorot\Documents\GitHub\scrolling-shooter'

**Comment by Frankenmiller** [comment]
Try renaming the images folder as img

**Comment by Zoroththeawesome** [comment]
yeah I just found that and did that. no idea how you had it working on your end with the name being wrong. I copied over everything from images to img because the code uses img always

**Comment by Frankenmiller** [comment]
Yeah you might have to rework it a little

I’ve starred all the repositories under your profile, will you do me the favor please of starring all of my too, about 20 projects

Bryan Allen Junior Software Developer
***@***.***
📄https://www.linkedin.com/in/frankenmiller
🧑🏽‍💻https://github.com/frankenmiller
📊public.tableau.com/app/profile/frankenmiller
📱WhatsApp +264813643785

**Comment by Zoroththeawesome** [comment]
I have no idea what you are talking about my friend. I just made this account so the only repository I have is a little demo how to use github thing I was following along with. don't know what starring is either.

**Comment by Frankenmiller** [comment]
I went to you profile page at https://github.com/Zoroththeawesome <https://github.com/Zoroththeawesome> and clicked all of the stars on the repositories next to your name, two in total. Later today you can click some of the stars of my repositories, under my profile. It’s quick way we can help each other get hired. I reached out to you on LinkedIn to do the same, for “endorsements”. I gave you like 25 endorsements but you haven’t given me any in return yet. All you have to do is click on the stars for GitHub and on the “endorse” buttons for LinkedIn.

Bryan Allen Junior Software Developer
***@***.***
📄https://www.linkedin.com/in/frankenmiller
🧑🏽‍💻https://github.com/frankenmiller
📊public.tableau.com/app/profile/frankenmiller
📱WhatsApp +264813643785

**Comment by Zoroththeawesome** [comment]
when I click on the stars by your projects it just brings me back to your profile? Won't they see through this?

**Comment by Zoroththeawesome** [comment]
anyways this issue is solved. can you mark it as resolved?

**Comment by Frankenmiller** [comment]
I’ll mark it as solved early tomorrow , I’m in bed with my iPhone, the floor of my apartment is cold 🥶 I was comfortable resting before sleep

**Comment by Zoroththeawesome** [comment]
sounds good. goodnight. I'll make some levels tonight. also heads up, don't think the boxes are working right. the wooden boxes I think are meant to be solid blocks by the way you are using them in game, but the guy just falls right through them. I would like them to be solid objects.

**Comment by Frankenmiller** [comment]
I saw how to do that, turn on/off collision on those boxes. I’ll do that today. And I’ll try adding ice themed assets to game and map editor, in preparation building level II/III

Happy we’ve got it up running on your screen finally. I’m doing sound FX’s today and game music first tho, and smooth level transitions. I’ll work on those blocks a little, and we should have ideas for new assets could be added.

Now that both of us have it opens on our screens we must be wary of “merge conflicts”

**Comment by Frankenmiller** [comment]
Issue closed Saturday 2022/JUL/16
