### ISSUE TITLE
Inconsistent spacing causing Errors and making editing difficult.

### ISSUE THREAD

**Issue by Zoroththeawesome** [Frankenmiller/scrolling-shooter#2]
There is inconsistant spacing within this code causing the following error:
"IndentationError: unindent does not match any outer indentation level" when trying to edit code. This is because whatever python platform you are using does not automatically turn tabs into spaces. Apparently, the standard is to use spaces as not all tabs are the same lengths. In order to fix this issue that is causing (and if what I have found online is any indication) will continue to cause errors I am changing all tabs to the appropriate number of spaces. I am attaching some articles and other online explanations to ensure you understand the problem. You will need to go into your settings and if able on your editor, set it so tabs are auto converted to spaces.
https://careerkarma.com/blog/python-indentationerror/
https://pythonawesome.com/a-python-script-to-turn-tabs-into-spaces-the-right-way/#

As you can see the arrows are tabs and the dots are spaces. Here is an example of this inconstancy within the code. Probably why the code is so "breakable" as you put it.
![image](https://user-images.githubusercontent.com/109387120/179339735-02fe8902-b833-41c1-8dc8-0ac1d0c9ee64.png)

**Comment by Zoroththeawesome** [comment]
when I am done, I will push my branch in to be added to the main.

**Comment by Zoroththeawesome** [comment]
trying to get it to branch and merger right but too tired going to bed. will get it to work tomorrow. fixes have been made though. also started making the wooden box a breakable object.

**Comment by Frankenmiller** [comment]
You're adusting filepaths to accomodate a file that doesn't belong in our project, it was only there as reference to compare some the planned functions against

Issue closed 2022-JUL-16 by FRANKENMILLER

**Comment by Zoroththeawesome** [comment]
frankenmiller I cant edit the code if you keep using tabs and don't use spaces. you have completely missed the point.

**Comment by Zoroththeawesome** [comment]
I haven't changed any file paths

**Comment by Frankenmiller** [comment]
It was created in VS code, it’s got its own formatting for python indentation. VS code is recognized by GitHub desktop, and will give you option says OPEN IN VSCODE. You’re using an IDE called spider, I don’t know this one but it might do that to your code, so I record VS code just b/c it’s the software I was taught to utilize best

I’ve got another commit coming up in next hour or so, then going put shooter project away work on Coursera stuff. You can checkout the files and adjust the grenade and gun shot kill values you wanted

Bryan Allen Junior Software Developer
***@***.***
📄https://www.linkedin.com/in/frankenmiller
🧑🏽‍💻https://github.com/frankenmiller
📊public.tableau.com/app/profile/frankenmiller
📱WhatsApp +264813643785

**Comment by Frankenmiller** [comment]
This is what code looks like in VS, you see looks sharp. I’m using neither tabs nor spaces, the software is simply auto formatting all the code and colorizing it. there’s all sorts of plug-in toys VS code utilizes to help its developers code faster with far less errors. There are many hotkeys you can learn to utilize in order speed up your code writing and make it cleaner too. I will help you learn these things



Bryan Allen Junior Software Developer
✉️ ***@***.***
📄 https://www.linkedin.com/in/frankenmiller
🧑🏽‍💻 https://github.com/frankenmiller
📊 public.tableau.com/app/profile/frankenmiller
📱 WhatsApp +264813643785
